### PR TITLE
Fix travis

### PR DESCRIPTION
**Pull request by ilyakrasnov**
@bdbradley @ltsinh @PaleoGuy2012 @Nikkovichert After talking to Barry yesterday I noticed that Travis CI was lacking a config file. I fixed it in this branch (fix-travis).

In order to practice our process, I'm waiting for 2 👍 from either of you and will merge the PR to master then. 

You will then see failing tests (but travis works now) -  would be great if you then try to fix failing tests 😄

### CODE REVIEW

**Comment by PaleoGuy2012** [comment]
Thumbs up on Merge from Ryan.

**Comment by ltsinh** [comment]
Thumbs up from me as well.

**Comment by Nikkovichert** [comment]
I dunno, it didn't pass the Travis CI tests.... kidding, I'm sure it's great. I still haven't actually looked at that video about how Travis CI works, but I'll do that right now

**Comment by ilyakrasnov** [comment]
@Nikkovichert You're correct - it didn't pass the tests but it came through up until the tests - previously it didn't even execute them due to failing configuration.

**Pull request merged**
